Repository dfe-analytical-services/eesyapi.R, pull requests merged in 2024-10, with the labels that each got.

#32 Updating examples - 2 Oct 24
  R/example_id.R
  tests/testthat/testdata/example_publication_catalogue.rds
  tests/testthat/testdata/example_publication_datasets.rds
Labels: test snapshot update, example-ids

#33 Updating get_meta to handle 3-col info on filters and indicators
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/get_meta.R
  man/parse_meta_indicator_columns.Rd
  tests/testthat/seed_tests.R
  tests/testthat/test-get_meta.R
  tests/testthat/testdata/example_meta_parsed.rds
  tests/testthat/testdata/example_meta_unparsed.rds
Labels: enhancement

#28 Features/post data query
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/api_url.R
  R/api_url_query.R
  R/api_url_query_utils.R
  R/convert_api_filter_type.R
  R/example_id.R
  R/examples.R
  R/get_dataset.R
  R/get_meta.R
  R/http_request_error.R
  R/post_dataset.R
  R/post_dataset_utils.R
  R/query_dataset.R
  R/validation_rules.R
  _pkgdown.yml
  man/api_url.Rd
  man/convert_api_filter_type.Rd
  man/example_geography_query.Rd
  man/example_id.Rd
  man/example_json_query.Rd
  man/get_dataset.Rd
  man/get_meta.Rd
  man/get_meta_response.Rd
  man/parse_meta_filter_columns.Rd
  man/parse_meta_filter_item_ids.Rd
  man/parse_meta_location_ids.Rd
  man/parse_meta_time_periods.Rd
  man/parse_tojson_filter.Rd
  man/parse_tojson_filter_eq.Rd
  man/parse_tojson_filter_in.Rd
  man/parse_tojson_geographies.Rd
  man/parse_tojson_indicators.Rd
  man/parse_tojson_location.Rd
  man/parse_tojson_params.Rd
  man/parse_tojson_time_periods.Rd
  man/parse_tourl_filter_in.Rd
  man/post_dataset.Rd
  man/query_dataset.Rd
  man/validate_ees_filter_type.Rd
  man/validate_ees_id.Rd
  man/validate_time_periods.Rd
  tests/testthat/seed_tests.R
  tests/testthat/test-http_request_error.R
  tests/testthat/test-query_dataset.R
  tests/testthat/test-validation.R
  tests/testthat/testdata/example_json-from-file_dataset.rds
  tests/testthat/testdata/example_json-from-string_dataset.rds
  tests/testthat/testdata/example_meta_parsed.rds
  tests/testthat/testdata/example_meta_unparsed.rds
  tests/testthat/testdata/example_post_dataset.rds
  tests/testthat/testdata/example_publication_catalogue.rds
  tests/testthat/testdata/example_publication_datasets.rds
  tests/testthat/testdata/test_query.json
Labels: new feature

#34 Translate data sqids
  DESCRIPTION
  NAMESPACE
  R/api_url.R
  R/eesyapi-package.R
  R/examples.R
  R/get_dataset.R
  R/get_meta.R
  R/parse_api_dataset.R
  R/parse_sqids.R
  R/post_dataset.R
  R/post_dataset_utils.R
  _pkgdown.yml
  man/api_url.Rd
  man/eesyapi-package.Rd
  man/example_data_raw.Rd
  man/get_dataset.Rd
  man/get_meta.Rd
  man/get_meta_response.Rd
  man/parse_api_dataset.Rd
  man/parse_meta_filter_columns.Rd
  man/parse_meta_filter_item_ids.Rd
  man/parse_meta_location_ids.Rd
  man/parse_meta_time_periods.Rd
  man/parse_sqids_filters.Rd
  man/parse_sqids_indicators.Rd
  man/parse_sqids_locations.Rd
  man/parse_tojson_params.Rd
  man/post_dataset.Rd
  man/query_dataset.Rd
  tests/testthat/test-query_dataset.R
  tests/testthat/testdata/example_json-from-file_dataset.rds
  tests/testthat/testdata/example_json-from-string_dataset.rds
  tests/testthat/testdata/example_meta_parsed.rds
  tests/testthat/testdata/example_post_dataset.rds
Labels: new feature

#38 Add csv endpoint wrapper
  .lintr
  DESCRIPTION
  NAMESPACE
  R/api_url.R
  R/download_dataset.R
  R/utils.R
  _pkgdown.yml
  man/api_url.Rd
  man/download_dataset.Rd
  man/get_dataset.Rd
  man/get_meta.Rd
  man/get_meta_response.Rd
  man/parse_api_dataset.Rd
  man/post_dataset.Rd
  man/query_dataset.Rd
  man/toggle_message.Rd
  tests/testthat/test-api_url.R
  tests/testthat/test-download_dataset.R
Labels: new feature

#40 Vignettes/workflow
  .gitignore
  DESCRIPTION
  NEWS.md
  R/post_dataset.R
  vignettes/.gitignore
  vignettes/ees-api-workflow.Rmd
  vignettes/ees-data-catalogue-details-api-data-set.png
  vignettes/ees-data-catalogue-find-api-data-set.png
Labels: documentation

#51 Update main workflow vignette to cover filter columns
  vignettes/ees-api-workflow.Rmd
Labels: documentation

#53 Updated documentation for example_id function
  R/examples.R
  man/example_data_raw.Rd
  man/example_id.Rd
Labels: documentation

#54 Add in test environment connections
  NAMESPACE
  R/api_url.R
  R/examples.R
  R/get_data_catalogue.R
  R/get_dataset.R
  R/get_meta.R
  R/get_publications.R
  R/parse_api_dataset.R
  R/post_dataset.R
  R/query_dataset.R
  R/utils.R
  R/validation_rules.R
  man/api_url.Rd
  man/default_api_version.Rd
  man/default_ees_environment.Rd
  man/example_id.Rd
  man/get_data_catalogue.Rd
  man/get_dataset.Rd
  man/get_meta.Rd
  man/get_meta_response.Rd
  man/get_publications.Rd
  man/parse_api_dataset.Rd
  man/post_dataset.Rd
  man/query_dataset.Rd
  man/validate_api_version.Rd
  man/validate_ees_environment.Rd
  tests/testthat/seed_tests.R
  tests/testthat/test-api_url.R
  tests/testthat/test-get_meta.R
  tests/testthat/test-preview_dataset.R
  tests/testthat/test-query_dataset.R
  tests/testthat/testdata/example_json-from-file_dataset.rds
  tests/testthat/testdata/example_json-from-string_dataset.rds
  tests/testthat/testdata/example_meta_parsed.rds
  tests/testthat/testdata/example_meta_unparsed.rds
  tests/testthat/testdata/example_post_dataset.rds
  tests/testthat/testdata/example_publication_catalogue.rds
  tests/testthat/testdata/example_publication_datasets.rds
  tests/testthat/testdata/test_query.json
  vignettes/ees-api-workflow.Rmd
Labels: test snapshot update, example-ids, Test data

#60 Getting started docs (take 2)
  DESCRIPTION
  NEWS.md
  README.md
  tests/testthat/testdata/example_publication_catalogue.rds
  vignettes/eesyapi.Rmd
Labels: documentation
